### ISSUE TITLE
Also the reverse?

### ISSUE THREAD

**Issue by wmertens** [getify/eslint-plugin-arrow-require-this#2]
I love the double arrow for shorthand, I think it improves legibility, so it would be cool if this plugin could also be configured to only allow `function` if `this` is used in the function, maybe with an extra required comment to indicate the function is expected to be called as a method

**Comment by getify** [comment]
The precedent in ESLint (which I find a bit strange, but alas...) seems to basically be that "never" is the reverse of the rule (which is of course different from the absence of the rule).

So it seems like `["error","never"]` would just disallow `this` in arrow functions... which has the effect I think you're asking for, that any `this` found in the code would NOT be allowed in an arrow, and thus would have to have been in something other than an arrow.

Do I have that correct?

**Comment by wmertens** [comment]
Hmm, no, I would like all use of `function` to be discouraged, except when it cannot be avoided due to having to use a passed `this` instead of the lexical `this`.

For example, if you need to pass some callback to a library that will be called with an certain object on `this`, you can't use arrow.

In both your favorite code and mine, this rule would need to analyze the use of `function` and decide if it's approriate, but the error would be different, depending on the configuration.

**Comment by getify** [comment]
Thanks for the clarifications and for sharing your ideas.

What you describe is not really the reverse of this rule. I think it may be more like the converse (or inverse) of this rule, but I'm not even sure of that.

Would you still want to support the "nested" option? Like, would `foo(..)` below report an error or be OK, since it itself doesn't have a `this` (even though its *nested* `bar(..)` does)?

```js
function foo() {
   return function bar() {
      return this.x;
   };
}
```

I'm guessing you probably wouldn't want to allow that, since there's absolutely no reason for `foo()` to be a function just because `bar()` might need to be a function. Thus, I imagine you'd probably want your rule to not support "nested" mode.

----

I can't imagine any way that this one rule, being named "arrow-require-this", can do both things as we've mutually described them, and still make any sense. The only way it occurs to me to "combine" your rule and my rule in the same plugin would be to rename this plugin to just "require-this", and have two separate rules, one for "arrow" and one for "function" (or "non-arrow"), that in some respects did similar things (with the chosen function-type) but in other respects did fairly different things.

Also, you're hinting at having parts of your rule dependent either on the nature of the call-site, or even a comment nearby it, etc. I don't think that at all applies to my intended rule, so that's a further divergence.

I don't see at the moment that it makes sense to expand the scope of this plugin in the way being contemplated.

Honestly, I think your rule might be better served as a separate plugin/rule. You could clone this repo, and literally just change a couple of lines to not refer to arrow functions but rather regular functions. And depending on if you don't want to allow the relaxed "nested" mode, your plugin would be even quite a bit simpler.

----

All that aside, the idea I mentioned earlier in the thread, of "never" mode, still seems reasonable. I will definitely consider that part.

**Comment by wmertens** [comment]
Thanks for the detailed analysis and "never" mode! You are probably right that the converse is too different to be covered by this plugin. FWIW I'm not too bothered
by the nested case.

**Comment by PinkaminaDianePie** [comment]
Had exactly the same case. But I still agree it's out of the scope of that plugin.
